CREATE ROLE ADVIKA_ReadOnly;
CREATE ROLE ADVIKA_ReadWrite;
CREATE ROLE APURVA_ReadOnly;
CREATE ROLE APURVA_ReadWrite;
CREATE ROLE KHUSHBOO_ReadOnly;
CREATE ROLE KHUSHBOO_ReadWrite;
CREATE ROLE PRERANA_ReadOnly;
CREATE ROLE PRERANA_ReadWrite;


CREATE USER ASHARMA
  DEFAULT_ROLE = ADVIKA_ReadOnly
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER AKACHOLIYA
  DEFAULT_ROLE = APURVA_ReadOnly
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER KBOOLCHANDANI
  DEFAULT_ROLE = KHUSHBOO_ReadOnly
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER PMEHTA
  DEFAULT_ROLE = PRERANA_ReadOnly
  MUST_CHANGE_PASSWORD = FALSE;
-- Grant Roles to Users 
GRANT ROLE ADVIKA_ReadOnly TO USER ASHARMA;
GRANT ROLE ADVIKA_ReadWrite TO USER ASHARMA;
GRANT ROLE APURVA_ReadOnly TO USER AKACHOLIYA;
GRANT ROLE APURVA_ReadWrite TO USER AKACHOLIYA;
GRANT ROLE KHUSHBOO_ReadOnly TO USER Kboolchandani;
GRANT ROLE KHUSHBOO_ReadWrite TO USER Kboolchandani;
GRANT ROLE PRERANA_ReadOnly TO USER pmehta;
GRANT ROLE PRERANA_ReadWrite TO USER pmehta;

create warehouse SP500_STOCK_WH;
use warehouse sp500_stock_wh;

create database sp500_stock_dev;
use database sp500_stock_dev;

create schema dbt_KBOOLCHANDANI;
use schema dbt_kboolchandani;

-- Grant Permissions on New Dev Database (SP500_STOCK_DEV)
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE ADVIKA_ReadWrite;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE ADVIKA_ReadOnly;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE APURVA_ReadWrite;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE APURVA_ReadOnly;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE KHUSHBOO_ReadWrite;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE KHUSHBOO_ReadOnly;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE PRERANA_ReadOnly;
GRANT USAGE ON DATABASE SP500_STOCK_DEV TO ROLE PRERANA_ReadWrite;
-- GIVING READ/WRITE ACCESS ON DATABASE SP500_STOCK_DEV
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE ADVIKA_ReadWrite;
--write access
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN DATABASE SP500_STOCK_DEV TO ROLE ADVIKA_ReadWrite;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE ADVIKA_ReadWrite;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN DATABASE SP500_STOCK_DEV TO ROLE ADVIKA_ReadWrite;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE APURVA_ReadWrite;
--write access
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN DATABASE SP500_STOCK_DEV TO ROLE APURVA_ReadWrite;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE APURVA_ReadWrite;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN DATABASE SP500_STOCK_DEV TO ROLE APURVA_ReadWrite;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE KHUSHBOO_ReadWrite;
--write access
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN DATABASE SP500_STOCK_DEV TO ROLE KHUSHBOO_ReadWrite;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE KHUSHBOO_ReadWrite;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN DATABASE SP500_STOCK_DEV TO ROLE KHUSHBOO_ReadWrite;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE PRERANA_ReadWrite;
--write access
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN DATABASE SP500_STOCK_DEV TO ROLE PRERANA_ReadWrite;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE SP500_STOCK_DEV TO ROLE PRERANA_ReadWrite;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN DATABASE SP500_STOCK_DEV TO ROLE PRERANA_ReadWrite;



create database de_luminate_raw;
use database de_luminate_raw;

create schema sp500_stock;
use schema sp500_stock;



-- GIVING READ ACCESS ON DE_LUMINATE_RAW.SP500_STOCK
-- GIVING READ ACCESS ON DE_LUMINATE_RAW
GRANT USAGE ON DATABASE DE_LUMINATE_RAW TO ROLE ADVIKA_ReadOnly;
GRANT USAGE ON DATABASE DE_LUMINATE_RAW TO ROLE APURVA_ReadOnly;
GRANT USAGE ON DATABASE DE_LUMINATE_RAW TO ROLE KHUSHBOO_ReadOnly;
GRANT USAGE ON DATABASE DE_LUMINATE_RAW TO ROLE PRERANA_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE ADVIKA_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE TABLES IN DATABASE DE_LUMINATE_RAW TO ROLE ADVIKA_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE APURVA_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE APURVA_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE KHUSHBOO_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE KHUSHBOO_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE PRERANA_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN DATABASE DE_LUMINATE_RAW TO ROLE PRERANA_ReadOnly;
-- GIVING READ ACCESS ON SP500_STOCK
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA SP500_STOCK TO ROLE ADVIKA_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN SCHEMA SP500_STOCK TO ROLE ADVIKA_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA SP500_STOCK TO ROLE APURVA_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN SCHEMA SP500_STOCK TO ROLE APURVA_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA SP500_STOCK TO ROLE KHUSHBOO_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN SCHEMA SP500_STOCK TO ROLE KHUSHBOO_ReadOnly;
--read acess
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA SP500_STOCK TO ROLE PRERANA_ReadOnly;
GRANT SELECT, REFERENCES ON FUTURE VIEWS IN SCHEMA SP500_STOCK TO ROLE PRERANA_ReadOnly;
----------------------------------------------------------------
CREATE OR REPLACE STAGE DE_LUMINATE_RAW.SP500_STOCK.sp500_raw_stage;
CREATE OR REPLACE TABLE DE_LUMINATE_RAW.SP500_STOCK.RAW_STOCK_PRICES (
    DATE DATE,
    OPEN FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    CLOSE FLOAT,
    VOLUME FLOAT,
    NAME STRING
);
COPY INTO RAW_STOCK_PRICES
FROM (
    SELECT
        TO_DATE($1) AS DATE,
        TRY_TO_NUMBER($2) AS OPEN,
        TRY_TO_NUMBER($3) AS HIGH,
        TRY_TO_NUMBER($4) AS LOW,
        TRY_TO_NUMBER($5) AS CLOSE,
        TRY_TO_NUMBER($6) AS VOLUME,
        SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 1) AS NAME
    FROM @sp500_raw_stage
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';
select count(*) from  raw_stock_prices;


-- 1. Create the File Format
CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE TABLE COMPANIES_DETAILS_RAW (
    "Exchange" VARCHAR(50),
    "Symbol" VARCHAR(10),
    "Shortname" VARCHAR(255),
    "Longname" VARCHAR(255),
    "Sector" VARCHAR(100),
    "Industry" VARCHAR(100),
    "Currentprice" FLOAT,
    "Marketcap" NUMBER(38,0),
    "Ebitda" NUMBER(38,0),
    "Revenuegrowth" FLOAT,
    "City" VARCHAR(100),
    "State" VARCHAR(100),
    "Country" VARCHAR(100),
    "Fulltimeemployees" NUMBER,
    "Longbusinesssummary" TEXT,
    "Weight" FLOAT
);

COPY INTO COMPANIES_DETAILS_RAW
FROM @sp500_raw_stage/sp500_companies.csv
FILE_FORMAT = (FORMAT_NAME = csv_sp500_format)
ON_ERROR = 'CONTINUE';

-- 2. Grant select on the specific table
GRANT SELECT ON TABLE DE_LUMINATE_RAW.SP500_STOCK.COMPANIES_DETAILS_RAW TO ROLE KHUSHBOO_READONLY;
GRANT SELECT ON TABLE DE_LUMINATE_RAW.SP500_STOCK.COMPANIES_DETAILS_RAW TO ROLE KHUSHBOO_READWRITE;