version: 2

sources:
  - name: raw
    database: DE_LUMINATE_RAW
    schema: SP500_STOCK
    tables:
      - name: raw_stock_prices
        description: "Raw SP500 stock price data including open, high, low, close, and volume."
      - name: companies_details_raw
        description: "Raw SP500 companies data including sector and industry"




