version: 2

models:
 - name: v_yearly_performance_summary
   description: "Summarizes yearly stock performance and calculates annual returns and drawdowns."
   columns:
      - name: ticker
        tests: [not_null]
      - name: year
        tests: [not_null]