version: 2

models:
  - name: v_daily_market_movers
    description: "Shows top 10 daily gainers, losers, and most traded stocks for the latest trading day."
    columns:
      - name: ticker
        tests: [not_null]
      - name: category
        tests: [not_null]

  - name: v_stock_trend_indicators
    description: "Provides moving average trend indicators with technical signals (Golden Cross / Death Cross)."
    columns:
      - name: ticker
        tests: [not_null]
      - name: signal
        description: "Technical signal indicating market trend crossover."

  